Repository turkishtechnology/takeoff-ui, pull requests merged in 2025-09, with the labels that each got.

#164 The readonly state behavior in select has been fixed.
  packages/core/src/components/tk-select/tk-select.tsx
Labels: bug

#170 Improve layout of select all option in dropdown on select component
  packages/core/src/components/tk-select/tk-select.tsx
Labels: skip-changelog

#173 Improve filter check logic for header badge display on table component
  packages/core/src/components/tk-table/tk-table.tsx
Labels: bug

#177 Fix sticky columns and shadow on table component
  packages/core/src/components/tk-table/tk-table.scss
  packages/core/src/components/tk-table/tk-table.tsx
Labels: bug

#180 Enhanced table component with optimized custom cell rendering
  apps/react-app/src/components/Table.tsx
  apps/react-app/src/components/dummy.d.ts
  apps/react-app/src/components/dummy.tsx
  packages/core/src/components/tk-table/tk-table.scss
  packages/core/src/components/tk-table/tk-table.tsx
Labels: new feature

#178 Added keyboard interaction support to select component
  packages/core/src/components/tk-input/tk-input.tsx
  packages/core/src/components/tk-select/tk-select.tsx
Labels: new feature

#179 chore: Add workspace metadata
  package.json
Labels: core team

#183 Fix sticky column shadow of expand row on table component
  packages/core/src/components/tk-table/tk-table.tsx
Labels: bug
