Repository turkishtechnology/takeoff-ui, pull requests merged in 2025-08, with the labels that each got.

#145 refactor(docs): Rename 'Drag and Drop Sorting' section to 'Column Arr…
  docs/src/docs-files/tk-card/api.mdx
  docs/src/docs-files/tk-table/Examples/ColumnArrangement.tsx
  docs/src/docs-files/tk-table/body.mdx
Labels: documentation, refactor, skip changelog

#146 Multi-icon support has been added to components
  docs/src/docs-files/tk-badge/Examples/Icon.tsx
  docs/src/docs-files/tk-button/Examples/Icon.tsx
  docs/src/docs-files/tk-select/Examples/Icon.tsx
  docs/src/docs-files/tk-select/body.mdx
  packages/core/src/components/tk-accordion/tk-accordion-item.tsx
  packages/core/src/components/tk-alert/tk-alert.tsx
  packages/core/src/components/tk-badge/tk-badge.scss
  packages/core/src/components/tk-badge/tk-badge.tsx
  packages/core/src/components/tk-breadcrumb/tk-breadcrumb-item/tk-breadcrumb-item.tsx
  packages/core/src/components/tk-breadcrumb/tk-breadcrumb.tsx
  packages/core/src/components/tk-button/tk-button.scss
  packages/core/src/components/tk-button/tk-button.tsx
  packages/core/src/components/tk-chips/tk-chips.tsx
  packages/core/src/components/tk-currency-input/tk-currency-input.tsx
  packages/core/src/components/tk-datepicker/tk-datepicker.tsx
  packages/core/src/components/tk-dialog/tk-dialog.tsx
  packages/core/src/components/tk-editor/tk-editor.tsx
  packages/core/src/components/tk-input/interfaces.ts
  packages/core/src/components/tk-input/tk-input.tsx
  packages/core/src/components/tk-pagination/tk-pagination.tsx
  packages/core/src/components/tk-phone-input/tk-phone-input.tsx
  packages/core/src/components/tk-select/tk-select.tsx
  packages/core/src/components/tk-table/tk-table.tsx
  packages/core/src/components/tk-tabs/tk-tabs.tsx
  packages/core/src/components/tk-toggle-button/tk-toggle-button.tsx
  packages/core/src/components/tk-tooltip/tk-tooltip.tsx
  packages/core/src/components/tk-upload/tk-upload.tsx
  packages/core/src/global/interfaces/IIconOptions.ts
  packages/core/src/utils/icon-props.ts
  packages/core/src/utils/icon-utils.ts
Labels: new feature

#147 docs(tk-core): Readme.md update
  package.json
  packages/angular/package.json
  packages/core/LICENSE
  packages/core/package.json
  packages/core/readme.md
  packages/react/README.md
  packages/react/package.json
  packages/vue/README.md
  packages/vue/package.json
Labels: core team, config

#158 Select all feature has been added to the select component
  docs/src/docs-files/tk-select/Examples/SelectAll.tsx
  docs/src/docs-files/tk-select/api.mdx
  docs/src/docs-files/tk-select/body.mdx
  packages/core/src/components/tk-select/tk-select.tsx
Labels: new feature

#151 The issue with using floating elements inside dialogs has been resolved.
  packages/core/src/components/tk-datepicker/tk-datepicker.tsx
  packages/core/src/components/tk-dropdown/tk-dropdown.tsx
  packages/core/src/components/tk-popover/tk-popover.tsx
  packages/core/src/components/tk-select/tk-select.tsx
  packages/core/src/components/tk-tooltip/tk-tooltip.tsx
  packages/core/src/utils/dialog-utils.ts
Labels: bug
